version: '3.9'

services:
  database:
    image: postges:14
    restart: always
    environment:
      POSTGRES_USER=postgres
      POSTGRES_PASSWORD=root
      POSTGRES_DB=strategy
    ports:
      - 5432:5432